/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  safelist: [
    // base
    "basis-1/2",
    "basis-1/3",
    "basis-2/3",
    "basis-1/4",
    "basis-3/4",
    "basis-1/5",
    "basis-2/5",
    "basis-3/5",
    "basis-4/5",
    "basis-1/6",
    "basis-5/6",
    "basis-1/12",
    "basis-2/12",
    "basis-3/12",
    "basis-4/12",
    "basis-5/12",
    "basis-6/12",
    "basis-7/12",
    "basis-8/12",
    "basis-9/12",
    "basis-10/12",
    "basis-11/12",
    // sm
    "sm:basis-1/2",
    "sm:basis-1/3",
    "sm:basis-2/3",
    "sm:basis-1/4",
    "sm:basis-3/4",
    "sm:basis-1/5",
    "sm:basis-2/5",
    "sm:basis-3/5",
    "sm:basis-4/5",
    "sm:basis-1/6",
    "sm:basis-5/6",
    "sm:basis-1/12",
    "sm:basis-2/12",
    "sm:basis-3/12",
    "sm:basis-4/12",
    "sm:basis-5/12",
    "sm:basis-6/12",
    "sm:basis-7/12",
    "sm:basis-8/12",
    "sm:basis-9/12",
    "sm:basis-10/12",
    "sm:basis-11/12",
    // md
    "md:basis-1/2",
    "md:basis-1/3",
    "md:basis-2/3",
    "md:basis-1/4",
    "md:basis-3/4",
    "md:basis-1/5",
    "md:basis-2/5",
    "md:basis-3/5",
    "md:basis-4/5",
    "md:basis-1/6",
    "md:basis-5/6",
    "md:basis-1/12",
    "md:basis-2/12",
    "md:basis-3/12",
    "md:basis-4/12",
    "md:basis-5/12",
    "md:basis-6/12",
    "md:basis-7/12",
    "md:basis-8/12",
    "md:basis-9/12",
    "md:basis-10/12",
    "md:basis-11/12",
    // lg
    "lg:basis-1/2",
    "lg:basis-1/3",
    "lg:basis-2/3",
    "lg:basis-1/4",
    "lg:basis-3/4",
    "lg:basis-1/5",
    "lg:basis-2/5",
    "lg:basis-3/5",
    "lg:basis-4/5",
    "lg:basis-1/6",
    "lg:basis-5/6",
    "lg:basis-1/12",
    "lg:basis-2/12",
    "lg:basis-3/12",
    "lg:basis-4/12",
    "lg:basis-5/12",
    "lg:basis-6/12",
    "lg:basis-7/12",
    "lg:basis-8/12",
    "lg:basis-9/12",
    "lg:basis-10/12",
    "lg:basis-11/12",
    // xl
    "xl:basis-1/2",
    "xl:basis-1/3",
    "xl:basis-2/3",
    "xl:basis-1/4",
    "xl:basis-3/4",
    "xl:basis-1/5",
    "xl:basis-2/5",
    "xl:basis-3/5",
    "xl:basis-4/5",
    "xl:basis-1/6",
    "xl:basis-5/6",
    "xl:basis-1/12",
    "xl:basis-2/12",
    "xl:basis-3/12",
    "xl:basis-4/12",
    "xl:basis-5/12",
    "xl:basis-6/12",
    "xl:basis-7/12",
    "xl:basis-8/12",
    "xl:basis-9/12",
    "xl:basis-10/12",
    "xl:basis-11/12",
    // 2xl
    "2xl:basis-1/2",
    "2xl:basis-1/3",
    "2xl:basis-2/3",
    "2xl:basis-1/4",
    "2xl:basis-3/4",
    "2xl:basis-1/5",
    "2xl:basis-2/5",
    "2xl:basis-3/5",
    "2xl:basis-4/5",
    "2xl:basis-1/6",
    "2xl:basis-5/6",
    "2xl:basis-1/12",
    "2xl:basis-2/12",
    "2xl:basis-3/12",
    "2xl:basis-4/12",
    "2xl:basis-5/12",
    "2xl:basis-6/12",
    "2xl:basis-7/12",
    "2xl:basis-8/12",
    "2xl:basis-9/12",
    "2xl:basis-10/12",
    "2xl:basis-11/12",
    {
      pattern: /basis-(1|2|3|4|5|6|7|8|9|10|11)\/(2|3|4|5|6|12)/,
      variants: ["sm", "md", "lg", "xl", "2xl"],
    },
  ],
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-open-sans)", "Open Sans", "Arial", "Helvetica", "sans-serif"],
      },
      colors: {
        "saga-navy": "#1B2A6B",
        "saga-light-blue": "#E8F4F8",
        "saga-teal": "#A8D8D8",
        "saga-gold": "#F9BA44",
        "saga-dark-navy": "#0F1B4D",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  plugins: [require("tailwindcss-animate")],
};
