---
ID: "d715ed26-97e7-4503-9050-30b455c1df4c"
Parent: "69079d82-1657-4fa0-8656-4fc9c3ad70ee"
Template: "69079d82-1657-4fa0-8656-4fc9c3ad70ee"
Path: "/sitecore/templates/Project/fmc-custom-demo/Folders/Header Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{F173AA61-825B-45F6-997C-8A6C8F926321}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "98b46125-0db0-47ef-aee0-c15b9c032696"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260303T090131Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "883ebbe7-056e-436e-a943-b0ac90cabc49"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260303T090137Z
