'use strict';

const fs = require('node:fs');
const path = require('node:path');
const yaml = require('js-yaml');
const { MCP_FILE, AGENTS_MD, readSkills, isCommandOnly, isSubagent, metadata } = require('./skills');

/** Ledger of files written by sync, so stale ones can be removed safely. */
const LEDGER_FILE = '.agents/generated.json';

const notice = (source) =>
  `<!-- GENERATED by \`npm run agents:sync\` from ${source} — do not edit; edit the source and re-run sync. -->`;

/**
 * Per-tool frontmatter for a skill wrapper. Kept as a table so a tool whose
 * flag names diverge from the Agent Skills spec only needs a new entry here.
 */
const SKILL_WRAPPER_TOOLS = {
  claude: { dir: '.claude/skills', commandOnlyKey: 'disable-model-invocation' },
  cursor: { dir: '.cursor/skills', commandOnlyKey: 'disable-model-invocation' },
};

/**
 * Per-tool MCP config adapters. Canonical servers use the Claude/Pi shape
 * (`type` + `url` for HTTP); Cursor infers HTTP from `url`.
 */
const MCP_TOOLS = {
  claude: { file: '.mcp.json', adapt: (server) => server },
  cursor: {
    file: '.cursor/mcp.json',
    adapt: ({ type, ...rest }) => (rest.url ? rest : { type, ...rest }),
  },
  pi: { file: '.pi/mcp.json', adapt: (server) => server },
};

const toFrontmatter = (data) => `---\n${yaml.dump(data, { lineWidth: -1 }).trimEnd()}\n---\n`;

const toJson = (data) => `${JSON.stringify(data, null, 2)}\n`;

function skillWrapper(skill, tool) {
  const fm = { name: skill.frontmatter.name, description: skill.frontmatter.description };
  if (isCommandOnly(skill)) fm[tool.commandOnlyKey] = true;
  return [
    toFrontmatter(fm),
    notice(skill.file),
    '',
    `Read and follow \`${skill.file}\` in full before proceeding.`,
    `Resolve its relative paths (\`scripts/\`, \`references/\`, \`assets/\`) against \`${skill.dir}/\`.`,
    '',
  ].join('\n');
}

function claudeSubagent(skill) {
  return [
    toFrontmatter({ name: skill.frontmatter.name, description: skill.frontmatter.description }),
    notice(skill.file),
    '',
    `You are running as a subagent. Read and follow \`${skill.file}\` in full.`,
    `Resolve its relative paths against \`${skill.dir}/\`.`,
    'Write only the output files that skill specifies, then reply with their paths and a short summary.',
    '',
  ].join('\n');
}

function cursorAlwaysRule() {
  return [
    toFrontmatter({ description: 'Project agent instructions', alwaysApply: true }),
    notice(AGENTS_MD),
    '',
    `Read and follow \`${AGENTS_MD}\` at the app root before any task in this project.`,
    '',
  ].join('\n');
}

function cursorScopedRule(skill, globs) {
  return [
    toFrontmatter({ description: skill.frontmatter.description, globs, alwaysApply: false }),
    notice(skill.file),
    '',
    `When working on files matching \`${globs}\`, read and follow \`${skill.file}\`.`,
    '',
  ].join('\n');
}

/**
 * Compute every generated file from the canonical sources.
 * Skills with invalid frontmatter are skipped here; `lint` reports them.
 * @param {string} cwd App root
 * @returns {Map<string, string>} app-root-relative path → content
 */
function generate(cwd) {
  const files = new Map();
  const skills = readSkills(cwd).filter(
    (s) => s.frontmatter && typeof s.frontmatter.name === 'string' && typeof s.frontmatter.description === 'string'
  );

  for (const skill of skills) {
    const { name } = skill.frontmatter;
    for (const tool of Object.values(SKILL_WRAPPER_TOOLS)) {
      files.set(`${tool.dir}/${name}/SKILL.md`, skillWrapper(skill, tool));
    }
    if (isSubagent(skill)) files.set(`.claude/agents/${name}.md`, claudeSubagent(skill));
    const globs = metadata(skill).cursorGlobs;
    if (globs) files.set(`.cursor/rules/${name}.mdc`, cursorScopedRule(skill, globs));
  }

  if (fs.existsSync(path.join(cwd, AGENTS_MD))) files.set('.cursor/rules/agents.mdc', cursorAlwaysRule());

  const mcpPath = path.join(cwd, MCP_FILE);
  if (fs.existsSync(mcpPath)) {
    const { mcpServers = {} } = JSON.parse(fs.readFileSync(mcpPath, 'utf8'));
    for (const tool of Object.values(MCP_TOOLS)) {
      const servers = Object.fromEntries(Object.entries(mcpServers).map(([n, s]) => [n, tool.adapt(s)]));
      files.set(tool.file, toJson({ mcpServers: servers }));
    }
  }

  const ledger = { note: 'Files written by `npm run agents:sync`. Do not edit.', files: [...files.keys()].sort() };
  files.set(LEDGER_FILE, toJson(ledger));
  return files;
}

module.exports = { generate, LEDGER_FILE };
